# 모던 JavaScript 듀토리얼 day03

- 읽을파트: [파트 1 11.5] 프라미스 API
- 평가: 유익, 예제로 쉽게 이해되었습니다

---

## [파트 1 11.5] 프라미스 API

- `Promise` 클래스에는 5가지 정적 메서드가 있습니다
  - Promise.all
    - `Promise.all`은 요소 전체가 프라미스인 배열(이터러블 객체)를 받고 새로운 프라미스를 반환합니다
    - 배열 안 프라미스가 모두 처리되면 새로운 프라미스가 이행되는데, 배열 안 프라미스의 결괏값을 담은 배열이 새로운 프라미스의 `result`가 됩니다
    - 배열 `result`의 요소 순서는 `Promise.all`에 전달되는 프라미스 순서와 상응합니다. 즉 첫번째 프라미스가 늦게 이행되더라도 배열의 첫번째 요소로 저장됩니다
    - `Promise.all`에 전달되는 프라미스 중 하나라도 거부되면, `Promise.all`이 반환하는 프라미스는 에러와 함께 바로 거부됩니다
    - 프라미스가 하나라도 거부되면 `Promise.all`은 즉시 거부되고 배열에 저장된 다른 프라미스의 결과는 완전히 무시됩니다. 즉, 이행된 결과도 무시됩니다.
      `fetch`를 사용해 호출 여러 개를 만들면, 그 중 하나가 실패하더라도 호출은 계속 일어납니다
    - `Promise.all(...)`의 요소로 프라미스가 아닌 객체일 경우 요소 '그대로' 결과 배열에 전달됩니다
  - Promise.allSettled
    - `Promise.allSettled`는 모든 프라미스가 처리될 때까지 기다립니다. 반환되는 배열은 다음과 같은 요소를 갖습니다
      - 응답이 성공한 경우 - `{status:"fulfilled", value:result}`
      - 에러가 발생한 경우 - `{status:"rejected", reason:error}`
  - Promise.race
    - 가장 먼저 처리되는 프라미스의 결과(혹은 에러)를 반환합니다
  - Promise.resolve
    - `Promise.resolve(value)`는 결괏값이 `value`인 이행상태 프라미스를 생성합니다
  - Promise.reject
    - `Promise.reject(error)`는 결괏값이 `error`인 거부 상태 프라미스를 생성합니다
